### ISSUE TITLE
Marvin creates a directory in the home directory, conflicting with AWS LAMBDA

### ISSUE THREAD

**Issue by Fakamoto** [PrefectHQ/marvin#853]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Marvin creates a directory in the home directory, conflicting with AWS LAMBDA as this is not allowed.
Marvin should have an option to avoid this.

### Reproduction

```python3
# Create a AWS LAMBDA function that uses marvin
```

### Versions

```Text
Version:		2.1.5
Python version:		3.11.7
OS/Arch:		darwin/arm64
```

**Comment by zzstoatzz** [comment]
hi @Fakamoto - thanks for the issue!

can you explain a bit more of what you're seeing?

I was thinking you might be talking about `~/.marvin`, which I suspected the pydantic settings might be creating due to our use of `env_file`, but I am not seeing this created automatically if I install / run marvin in a fresh containerized environment.

**Comment by zzstoatzz** [comment]
closing this, please let me know if this is still an issue for you!
